### ISSUE TITLE
Vertical text on the graphs may have visual artifacts

### ISSUE THREAD

**Issue by adem4ik** [FelixdelasPozas/TrayWeather#107]
TW: 1.21.0
OS: Windows 10 x64
- Open Forecast/Polution/UV graphs
- Take a look at the vertical text on the sides of the graphs
 
Result: some text looks unreadable and deformed
![image](https://user-images.githubusercontent.com/4707112/166248777-7557f61f-630c-4b73-897e-0983332e09a1.png) ![image](https://user-images.githubusercontent.com/4707112/166248849-d50246d0-54c6-4ba3-9761-018816113db4.png) ![image](https://user-images.githubusercontent.com/4707112/166248940-e0810c38-b50b-465f-8df8-5bfb684c2fd5.png)

It seems more noticeable with cyrillic letters (Russian/Ukrainian translation) 
![image](https://user-images.githubusercontent.com/4707112/166249448-9659f891-f820-4be6-95e3-7064f990e3ed.png) ![image](https://user-images.githubusercontent.com/4707112/166249698-8ae1ea6e-6e01-401e-8158-85f4b0a8c537.png) ![image](https://user-images.githubusercontent.com/4707112/166249979-96507ac6-d366-46e0-b886-3a0d1bbea8c8.png) ![image](https://user-images.githubusercontent.com/4707112/166249851-3cad3cd5-34b7-40c8-920b-d0294f88cd8a.png)

Also with Chinese symbols
![image](https://user-images.githubusercontent.com/4707112/166249242-5b98a19f-439e-4717-ab9e-40c1438c9730.png) ![image](https://user-images.githubusercontent.com/4707112/166249298-ae238a92-b5b8-42c9-998b-5e8fc6c1b262.png)

It's an old issue, I just managed to report it only now. I guess it may depend on the font used for that text.

**Comment by FelixdelasPozas** [comment]
Hi @adem4ik . 

It seems reasonably clear at least in my computer with the font default settings. But the that font is completely configurable so I'll look into it to see if it can be enhanced in those cases. Maybe letter hinting or spacing can be modified to get a better result.

Regards,
Félix.

**Comment by FelixdelasPozas** [comment]
In the picture from left to right: default, +1 size, +1 size +1 spacing.

![font](https://user-images.githubusercontent.com/12167134/166898383-cd1388bc-2d24-434f-bac9-b9008ca82041.png)

Ended using a bigger font (a little, just one point bigger) with more spacing between letters. I think this will allow for better letter hinting and readability. I'll add it in the next release.

**Comment by adem4ik** [comment]
Yes, the last screen (+1 size +1 spacing) looks definitely better. Thanks!

**Comment by FelixdelasPozas** [comment]
Brief update. 

When modifying the vertical text and size it seems that the text is automatically ellided in some translations (chinese in particular don't know why as the text is not really long, but only the first two characters are shown and then the dots). So I'm still looking into how to really fix it.

Options:
* Make the dialog a little bit bigger so the text has more space to grow. 
* Force un-elided text somehow inside the QChart class.

Regards, 
Félix.

**Comment by FelixdelasPozas** [comment]
Hi @adem4ik .

In the [latest release (1.21.2)](https://github.com/FelixdelasPozas/TrayWeather/releases/tag/1.21.2) I couldn't increase the font size, just the separation between letters (that I hope will make text more readable). Increasing the font size would make some localizations text appear elided and I didn't want to increase the dialog size to accommodate it.

Regards,
Félix.

**Comment by adem4ik** [comment]
Hello @FelixdelasPozas 

The read-ability is definitely better now, at least on Latin and Cyrillic:
![image](https://user-images.githubusercontent.com/4707112/172784336-a81960f8-7a44-4424-96d0-de45df5b2b4d.png)

But I find Chinese letters quite distorted. And actually the whole application has that problem:
![image](https://user-images.githubusercontent.com/4707112/172785676-ecf0b736-a692-4b33-a42f-cc9608287123.png)

I guess it is fine to close my issue at this state as Chinese letters' problem must be something different and requires different approach. Or mb it is just my local Windows' Chinese fonts configuration :/

**Comment by FelixdelasPozas** [comment]
Yes, chinese characters have the problem that in **bold font** are not easily visible. Too many "strokes" and very close to each other in a single character. Maybe a possibility will be not to use bold fonts in that translation. Let's keep the issue open, I'll look into it during the weekend.

Regards,
Félix.

**Comment by FelixdelasPozas** [comment]
Hi @zyh941.

Sorry to attach you to a running issue. We were having a discussion about text rendering in the latest versions and how could be improved. I have some questions about the Chinese text rendering:
* Is the current version readable without problems? Are some letters distorted or confusing?
* If there are some problems, will **not using bold fonts** solve them? (I mean, the text not in bold presents the same problems?)

Thanks in advance,
Félix.

**Comment by zyh941** [comment]
Hello,

  1.  I saw the issue discussion on Github. I just looked at my computer running Windows 10 in my office and find nothing strange. You can see that screenshot one shows a clear type view of Simple Chinese fonts. ( It is default font: Microsoft Yahei.) However, I need to check in my laptop running Windows 11 in my home tonight. I am not sure the one who submit this issue use the Microsoft Yahei font. As I know, I installed Windows 10 in English before and encountered a wide range of misaligned Chinese like the issue(no matter what program, where interface), but if I install Windows 10 in Simple Chinese, no such issue.
  2.  I usually make my taskbar on the top of the screen. Please look at my screenshot two, in my Windows 10 computer, the interface is too long and I cannot see or reach the button at the bottom( recently I have to use keyboard ‘tap’ and ‘enter’ to choose one of the bottom button…). And I also remember clearly that in my Windows 11 laptop, the interface is also too long, but the bottom buttons can display while the title of program is covered by system taskbar. Can you fix this?
Best regards,
Hong
***@***.***
***@***.***
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by FelixdelasPozas** [comment]
Hi @zyh941 . I am unable to the see the screenshots, could you upload them to the issue on github? I suppose you mean the configuration dialog, as it grew larger and larger after adding new things. Yes, I'm planning on doing a refactor to add another tab and reduce its height, as (depending on the user display resolution) it could present problems.

**Comment by zyh941** [comment]
Here are the screenshots
![2](https://user-images.githubusercontent.com/95530307/173084266-632b4731-d00b-43af-b5ba-282219f8d404.png)
![1](https://user-images.githubusercontent.com/95530307/173084277-460cd196-6765-4d7a-9150-4c98e27efb13.png)

**Comment by FelixdelasPozas** [comment]
Hi @adem4ik and @zyh941. 

In version [1.22](https://github.com/FelixdelasPozas/TrayWeather/releases/tag/1.22.0) the configuration dialog should have a more reasonable size. 
For version 1.23 I'll introduce a way to customize the chart fonts that will give the user control to solve the problems with the legend and axis texts. I'll close the issue until then.

Regards, 
Félix.
