### ISSUE TITLE
Switch to HTTPS, make geolocation ping optional

### ISSUE THREAD

**Issue by savchenko** [FelixdelasPozas/TrayWeather#109]
By default, the application calls http://ip-api.com/csv/ upon launch. This issue is to suggest two things:

1. Switch to HTTPS
2. Do not call anything until explicitly requested by a user

**Comment by FelixdelasPozas** [comment]
Hi @savchenko .

1 - Using HTTPS in **ip-api.com** requires a paid subscription to the geo-location service. Not much, about 150€ a year, but given that this app is completely free... The free service only allows for HTTP requests, up to 45 a minute or so, more that enough for our case.
2 - No geo-location calls should be made when you have 'Manual coordinates' in the configuration 'Location' tab. In any other case the calls should be done, as the application must know Longitude and Latitude coordinates to ask for the weather data in your location (that is what happens upon launch, ask for the current weather data so it can load and show the correct weather icon). 

Are you asking for an option to not make any network request until the user explicitly says so? Doesn't seem very practical to make the user use an "Update" every time.

Regards, 
Félix.

**Comment by FelixdelasPozas** [comment]
Closed as it is not really a software issue.
