### ISSUE TITLE
Text overlap in detailed weather view

### ISSUE THREAD

**Issue by savchenko** [FelixdelasPozas/TrayWeather#110]
Column labels and partially the Y scale:

![image](https://user-images.githubusercontent.com/300146/170923292-705bf9c4-d2f0-4171-b700-cecf56645818.png)

**Comment by FelixdelasPozas** [comment]
Hi @savchenko .

I suppose you're using the latest version (currently 1.21). Yes, that is an error when scaling the window for high DPI resolutions. I'll make the scaling a little bit larger to accommodate all the text, that should solve it. I'll be in the next release.

Regards,
Félix.

**Comment by FelixdelasPozas** [comment]
Hi @savchenko .

Try the [1.21.2 release](https://github.com/FelixdelasPozas/TrayWeather/releases/tag/1.21.2). The dialog should be a little bit bigger to accomodate the axis font. I hope this will fix it.

Regards,
Félix.

**Comment by FelixdelasPozas** [comment]
I'll close this issue as I'll suppose the problem has disappeared?

**Comment by FelixdelasPozas** [comment]
Hi @savchenko .

I've made some modifications to try to fix the problem in the [latest release (1.23)](https://github.com/FelixdelasPozas/TrayWeather/releases/tag/1.23.0). Please try it and report when you can. 
This will be the last attempt to fix it without modifying the QtCharts code. If this fails  I'll need to do it though. 

Regards, 
Félix.

**Comment by FelixdelasPozas** [comment]
@savchenko 

The dates follow the format of the title **Day (Hour)** so the second number is the hour of the day. The chart library adjusts the labels given the current chart zoom. In your image you have about 44 values (with 44 different dates) but just 12 x axis labels. 
Glad it is solved just by modifying the amount of labels and font size. I really didn't want to start modifying the Qt charts code!!
I'll close the issue then. 

Regards, 
Félix.
