### ISSUE TITLE
Suggestion: adding an option to NOT show "default clouds" when weather is refreshed

### ISSUE THREAD

**Issue by DRSAgile** [FelixdelasPozas/TrayWeather#113]
Félix, just as the name suggests, is already making people happy.

Yet, TrayWeather can make some people even happier if there would be an option to show a previous temperature/weather conditions figures/icons during the periodical fetching of new weather data instead of the "default clouds".

And only if the fetching will time out after thirty seconds or something, then those "default clouds" should be shown.

This option might help people who are getting distracted by the "blinking" of the tray area during the weather checkups. 

Thanks in advance.

**Comment by FelixdelasPozas** [comment]
Hi @DRSAgile .

Yes, I think is a good idea. The icon shown when asking for data is a cloud with a "refreshing" icon inside. It would be necessary to show it when starting the application (when there is not yet weather data loaded) but for the rest of the calls it can be hidden and shown the previous weather icon instead. Ony if the data call fails, it would show the error icon (red cloud with an X inside). 
I'll try to add it to the next release. 

Regards, 
Félix.

**Comment by FelixdelasPozas** [comment]
Hi @DRSAgile . 

In the [latest version (1.22)](https://github.com/FelixdelasPozas/TrayWeather/releases/tag/1.22.0) that icon is hidden. It is only shown when the user requests a refresh/update from the tray icon context menu, to show that the application is doing the work. 

Regards, 
Félix.
