### ISSUE TITLE
Help with translations for version 1.22

### ISSUE THREAD

**Issue by FelixdelasPozas** [FelixdelasPozas/TrayWeather#114]
Hello @adem4ik , @autergame, @datenshi888, @cthulkhu and @zyh941.

For the release 1.22 I've tried to make the configuration dialog smaller, so the Tray Icon and the Tray Icon Tooltip got its own tab. Not much has really changed in terms of texts. Only two new texts need to be added.
- **Icon**
- **Icon tooltip.**

![Clipboard01](https://user-images.githubusercontent.com/12167134/175475438-83c7b6d9-b08c-48bc-bcf2-86a6ee61f19c.png)

I didn't use "Tray Icon" and "Tray Icon Tooltip" to make the text shorter and avoid having additional buttons that appear when the tabs witdh is larger than the window width (little "arrow" buttons to change between tabs appear when a tab is not visible). I think is clear enough what "Icon" and "Tooltip" refers in the dialog, so the shorter the text, the better.

This is how it looks right now.
![lightconfig](https://user-images.githubusercontent.com/12167134/175476533-aed133ab-1b0f-4881-a884-a84fe4f41913.png)

Regards, 
Félix.

**Comment by zyh941** [comment]
Hi, the Chinese translation shows below:

  *   图标
  *   图标悬浮文字提示
Best regards,
Hong

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

From: Félix de las Pozas ***@***.***>
Sent: 2022年6月24日 14:34
To: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Subject: [FelixdelasPozas/TrayWeather] Help with translations for version 1.22 (Issue #114)


Hello @adem4ik<https://github.com/adem4ik> , @autergame<https://github.com/autergame>, @datenshi888<https://github.com/datenshi888>, @cthulkhu<https://github.com/cthulkhu> and @zyh941<https://github.com/zyh941>.

For the release 1.22 I've tried to make the configuration dialog smaller, so the Tray Icon and the Tray Icon Tooltip got its own tab. Not much has really changed in terms of texts. Only two new texts need to be added.

  *   Icon
  *   Icon tooltip.

[Clipboard01]<https://user-images.githubusercontent.com/12167134/175475438-83c7b6d9-b08c-48bc-bcf2-86a6ee61f19c.png>

I didn't use "Tray Icon" and "Tray Icon Tooltip" to make the text shorter and avoid having additional buttons that appear when the tabs witdh is larger than the window width (little "arrow" buttons to change between tabs appear when a tab is not visible). I think is clear enough what "Icon" and "Tooltip" refers in the dialog, so the shorter the text, the better.

This is how it looks right now.
[lightconfig]<https://user-images.githubusercontent.com/12167134/175476533-aed133ab-1b0f-4881-a884-a84fe4f41913.png>

Regards,
Félix.

**Comment by cthulkhu** [comment]
icon значок
icon tooltip підказка значка
execuse me for slow reacting =)

**Comment by adem4ik** [comment]
@cthulkhu It should start with the upper case, i.e. "Значок" & "Підказка значка"

**Comment by datenshi888** [comment]
Hi! Slovenian translation:

- Icon - Ikona

- Icon tooltip. - Namig ikone

**Comment by autergame** [comment]
Hello, Portuguese translation

- Ícone
- Texto do ícone.

**Comment by FelixdelasPozas** [comment]
Thank you all. [Version 1.22](https://github.com/FelixdelasPozas/TrayWeather/releases/tag/1.22.0) has been released (a little bit late, sorry for that).

Kind regards, 
Félix.
