### ISSUE TITLE
QtCharts link isn't clickable in About dialog

### ISSUE THREAD

**Issue by adem4ik** [FelixdelasPozas/TrayWeather#119]
Version: 1.22

1. Open About dialog
2. Click on https://github.com/qt/qtcharts/

Result: Nothing happens (other links work as expected)
![image](https://user-images.githubusercontent.com/4707112/176695446-24e14258-4aa9-4757-9f55-29ccdb2daf40.png)

**Comment by FelixdelasPozas** [comment]
Thanks @adem4ik . Fixed for the next release. 

Regards, 
Félix.
