### ISSUE TITLE
Configuration dialog should adapt its width right from the open

### ISSUE THREAD

**Issue by adem4ik** [FelixdelasPozas/TrayWeather#120]
Version: 1.22

1. Switch to Russian and save
2. Close Configuration dialog and open it once more

Result 1: All the tabs don't fit
![image](https://user-images.githubusercontent.com/4707112/176696902-720b8859-2c53-49ed-9587-d5bb105aefca.png)
Expected result: Configuration dialog width is adopted to the tabs (see Result 2)

3. Switсh to 3d tab (Значок)

Result 2: Configuration dialog width is adopted to the tabs
![image](https://user-images.githubusercontent.com/4707112/176697265-193f3291-5d13-44ad-b935-b9a9ccfd56f5.png)

Happens only with Russian & Ukrainian translation, as they have bigger words' length.

**Comment by FelixdelasPozas** [comment]
Fixed for the next release. The scroll buttons won't show and the dialog will try to adjust its size to see all tabs.

Regards, 
Félix.
