### ISSUE TITLE
Suggestion: Custom Tray Icons

### ISSUE THREAD

**Issue by legomangos** [FelixdelasPozas/TrayWeather#127]
Hello, as I said in the title, there should be a option to use custom icons instead of the built in ones.

**Comment by FelixdelasPozas** [comment]
Hello @legomangos .

There is already a discussion opened about this [here](https://github.com/FelixdelasPozas/TrayWeather/discussions/124). I'll close this as it'll be better to continue there. 

Regards, 
Félix.
