### ISSUE TITLE
Help with translations for version 1.24

### ISSUE THREAD

**Issue by FelixdelasPozas** [FelixdelasPozas/TrayWeather#128]
Hello @adem4ik , @autergame, @datenshi888, @cthulkhu, @zyh941 and @Krzysiu .

First my apologies to Krzysztof, I told you the release of the new version was going to be a week ago but I had other things to attend and I finally couldn't.

For the next release the new texts that needs translations are;
* "Error: "
* "No geolocation."
* "No pollution data."
* "No UV data."
* "No weather data."
* "Error requesting weather data."
* "Error requesting air quality data."
* "Error requesting ultraviolet radiation data."

The first five are intended to be in the tray icon tooltip text and due to limited space there (Windows only allows 127 characters) it should be as short as possible. 

Many thanks in advance. 
Félix.

**Comment by autergame** [comment]
Hello, Portuguese translation
- "Erro: "
- "Sem geolocalização."
- "Sem dados de poluição."
- "Sem dados de UV."
- "Sem dados meteorológicos."
- "Erro solicitando dados meteorológicos."
- "Erro solicitando dados de qualidade de ar."
- "Erro solicitando dados de radiação ultravioleta."

**Comment by zyh941** [comment]
Hi, the Chinese translation list as below:
• "出错："
• "无地理位置"
• "无污染数据"
• "无紫外线数据"
• "无天气数据"
• "请求天气数据时出错"
• "请求空气质量数据时出错"
• "请求紫外线辐射数据时出错"

Best regards,
Hong

**Comment by adem4ik** [comment]
Hi, here is Russian:

- "Ошибка: "
- "Нет геолокации."
- "Нет данных загрязнения."
- "Нет данных УФ-индекса."
- "Нет данных погоды."
- "Ошибка запроса данных погоды."
- "Ошибка запроса данных качества воздуха."
- "Ошибка запроса данных ультрафиолетового излучения."

**Comment by datenshi888** [comment]
Hi, Slovenian translation:

- "Napaka: "
- "Ni podatkov o geolokaciji."
- "Ni podatkov o onesnaženosti."
- "Ni podatkov o UV."
- "Ni vremenskih podatkov"
- "Napaka pri zahtevanju vremenskih podatkov."
- "Napaka pri zahtevanju podatkov o kakovosti zraka."
- "Napaka pri zahtevanju podatkov o ultravijoličnem sevanju."

**Comment by cthulkhu** [comment]
>     * "Error: "
Помилка
>     * "No geolocation."
Немає геолокації
>     * "No pollution data."
Немає даних забруднення
>     * "No UV data."
Немає даних УФ-індексу
>     * "No weather data."
Немає погодних даних
>     * "Error requesting weather data."
Помилка запиту погодних даних
>     * "Error requesting air quality data."
Помилка запиту якості повітря
>     * "Error requesting ultraviolet radiation data."
Помилка запиту даних УФ випромінення

**Comment by FelixdelasPozas** [comment]
Hi @Krzysiu. All translations except Polish for the new texts are done. When you translate the texts I'll release the version 1.24

Regards, 
Félix.

**Comment by adem4ik** [comment]
@FelixdelasPozas I suggest you to think about using external crowd translation service, i.e. https://weblate.org/ . Current translation workflow doesn't seem so effective as some translators may disappear someday.

**Comment by autergame** [comment]
> @FelixdelasPozas I suggest you to think about using external crowd translation service, i.e. https://weblate.org/ . Current translation workflow doesn't seem so effective as some translators may disappear someday.

I suggest https://crowdin.com

**Comment by FelixdelasPozas** [comment]
Hi @autergame and @adem4ik .

I've been looking a little bit into both options: Weblate and crowdin. Given that this project is very small (we barely have 1200 words in total) both seem a little overkill. Not really worth the price (crowdin appears to be free but rely on 'translation vendors' in its own marketplace, so not really). It won't be much of a difference for the people that want to collaborate, except registering and using another webpage apart from Github. 

I know that puts the weight of the translations on all of you, and I really *really* **really** appreciate the work you've been doing. But in the end if someone don't want or can't, I'll have rely on Google Translate for the translations as the process its completely voluntary. I've been doing it already for French and German translations since the beginning, as those people contacted me via email and when told to use github didn´t want to use it if I remember correctly. So it's not really a problem, as the Qt tools make the whole process very fast. 

Of course I'll prefer always a translation by any of you. This whole thing is free and while it has a bunch of downloads each release I think it doesn't qualify as "successful". In the end thing I like most about it is the collaboration you've all being doing. 

In fact I failed to add @isl6 to the initial post of this thread, my failure. I'll use also Google translate for the texts but if you provide the correct Korean translation I'll release the version 1.24.1 with that. My apologies, I just forgot. :frowning_face: 

Maybe putting a time limit will give this a little more "order" or a degree of expectancy. For example, if in a whole week a translation hasn't been provided I'll use Google translator. If someone can't do it by then they can always provide them later and I'll add them as a fix. We all probably live in different time zones and have different "rhythms" but that will make everyone sure that the translation they provide won't have to wait long for others to be released.

For now I'll translate the texts into Polish and publish the 1.24 asap.

Regards, 
Félix.

**Comment by FelixdelasPozas** [comment]
Release [1.24 have been published](https://github.com/FelixdelasPozas/TrayWeather/releases/tag/1.24.0). Thank you all for you patience. 

Regards, 
Félix.

**Comment by adem4ik** [comment]
@FelixdelasPozas https://hosted.weblate.org/hosting/ is free for open source projects as yours.
![image](https://user-images.githubusercontent.com/4707112/186031595-066974b0-c188-4532-8403-76d143071688.png)
