### ISSUE TITLE
Autostart problem

### ISSUE THREAD

**Issue by Xadeas** [FelixdelasPozas/TrayWeather#132]
Autostart doesn't seem to be able to read the config file at start up and opens as if it were freshly installed every time. Doesn't remember my manually entered coordinates nor my OpenWeather API key. Using the portable version on Win10, app is installed outside of Program Files so read/write privileges shouldn't be the issue.

**Comment by FelixdelasPozas** [comment]
Hi Xadeas. 

Is the application writing in the **TrayWeather.ini** file? Or is it empty? Check the permissions on the file, it should be writable for the portable mode to work and, for what you are telling, the application knows that the file is there but cannot write to or read from it.

Regards, 
Félix.

**Comment by Xadeas** [comment]
It is able to write and read since when I manually open the app after all my settings are suddenly back. For some reason initially at startup it cant?

**Comment by Xadeas** [comment]
Faulty HDD was the issue. Closing.
