### ISSUE TITLE
Change wind speed unit abbreviations, add knots

### ISSUE THREAD

**Issue by dziban303** [FelixdelasPozas/TrayWeather#137]
Really neat program, thanks for making it. I discovered it through winget. 

A recommendation: I'd suggest changing the (English, at least) wind speed units abbreviations in the tooltips to match commonly accepted forms. For example:

* `mil/h` should probably be `mph` or (the _much_ less common, but more correct) `mi/h`
* `feet/s` should be `ft/s`
* `met/sec` should be `m/s`

Additionally, I'd suggest adding knots to the available wind speed units (abbreviated `kts`) as it is widely used in the maritime and aviation industries.

Lastly, I'm not sure how useful it is to round windspeed to two decimal places; 0.05 mph, like in the screenshot below, is on the order of millimeters per second—well under the realistically achievable resolution of even professional meteorological equipment (e.g. the Belfort 50.5 solid state sensor has a resolution of 0.1 m/s, or 0.224 mph, more than four times higher, and cup-style anemometers are often worse). I'd just round that to the nearest tenth or whole number.

Unfortunately, I haven't touched C++ since about 1995, so doing a PR is beyond my abilities, haha. 

Thanks again for making the program!

![image](https://user-images.githubusercontent.com/7931765/197373948-213fe472-e18b-4b16-8fe0-81307adbb454.png)

**Comment by FelixdelasPozas** [comment]
Hi @dziban303 . For the next version (1.28) knots have been added and the units changed. I use metric units, so for imperial I'm going to trust someone who is used to them, thanks. And sorry for the laaaaarge delay.

Regards, 
Félix.
