### ISSUE TITLE
Text doesn't fit with Dark theme in "About" dialog

### ISSUE THREAD

**Issue by adem4ik** [FelixdelasPozas/TrayWeather#14]
Version: 1.4.2
OS: Windows 10 x64

1) Set Visual theme to "Dark"
2) Open "About..." dialog

Result: 
![image](https://user-images.githubusercontent.com/4707112/102719157-d0af9f00-4305-11eb-927b-1bbfa2c84af4.png)
Expected result:
![image](https://user-images.githubusercontent.com/4707112/102719167-eb821380-4305-11eb-9bd5-5ebc584a1aee.png)

**Comment by FelixdelasPozas** [comment]
Thanks for reporting it. The dark theme makes some widgets bigger (like the separator) and others smaller (like tab titles). It should be fixed the in [latest release](https://github.com/FelixdelasPozas/TrayWeather/releases/tag/1.4.3).  Try it, as I could only test it in Windows 7. 

Regards, 
Félix.

**Comment by adem4ik** [comment]
Yes, it is fixed in Win10. Thanks!
![image](https://user-images.githubusercontent.com/4707112/102721667-a9f96480-4315-11eb-85ea-f2c375a260fb.png)
