### ISSUE TITLE
[Not an issue] Is this project alive?

### ISSUE THREAD

**Issue by Patricek0056** [FelixdelasPozas/TrayWeather#144]
The last commit was committed in the October 2022, so I'm asking if is this project alive in the March 2023?

**Comment by Patricek0056** [comment]
Thank you for response, I'm closing this as completed.

**Comment by FelixdelasPozas** [comment]
If is something like adding a new translation, that can be done in minutes. But any other development that involves anything more complicated is something I can't do until the end of the Master's degree I'm currently doing, sorry. Thanks for you understanding.

Félix.
