### ISSUE TITLE
"Invalid reply from Geo-Locator server. Couldn't get location informaion. If you have a firewall change the configuration to allow this program to access the network"

### ISSUE THREAD

**Issue by Usv3re** [FelixdelasPozas/TrayWeather#146]
![error](https://github.com/FelixdelasPozas/TrayWeather/assets/137708184/a23ce187-52b8-4dcc-acb6-49ae4ca44cb4)

So I get this after starting. Tried to completely turn off both Windows Firewall and Anti-virus - no result

**Comment by FelixdelasPozas** [comment]
Hi @Usv3re, Sorry for the late reply. Did you solve it?

Regards, 
Félix.

**Comment by FelixdelasPozas** [comment]
As the author of the issue didn't reply with more information I suppose the issue has resolved. Closing it.
