### ISSUE TITLE
Invalid reply from OpenWeatherMap server.

### ISSUE THREAD

**Issue by catalin560** [FelixdelasPozas/TrayWeather#148]
I provided valid and active OWM API key but I get this error:
Invalid reply from OpenWeatherMap server.
Host requires authentication

**Comment by FelixdelasPozas** [comment]
Hi @catalin560 . 

The "Host requires authentication" message sometimes appear even if the API key is valid. If the configuration dialog tab for the OWM API returns that the key is ok (green message saying that it's ok), I suppose it's a temporary error from OWM. Sometimes it happens to me for the pollution tab, mostly. OWM servers have an uptime of ninety-something percent, that means that sometimes are unavailable for a brief period of time and it should resolve itself in a few hours.

Regards, 
Félix.

**Comment by FelixdelasPozas** [comment]
As the author of the issue didn't reply with more information I suppose the issue has resolved. Closing it.
