### ISSUE TITLE
Click on the "website" link doesn't work in Configuration window

### ISSUE THREAD

**Issue by adem4ik** [FelixdelasPozas/TrayWeather#15]
OS: Windows 10 x64
Version: 1.4.3

1) Open "Configuration" window
2) Click on the "website" link

Result: nothing happens
Expected result: http://openweathermap.org/appid is opened in the browser

![Configuration](https://user-images.githubusercontent.com/4707112/103100585-b5f26880-462c-11eb-88f4-a02aef3eb692.jpg)

Additional info:
- it doesn't work on 2 different PCs with Win10
- it is possible to copy the link by right mouse click menu
- it is possible to open the links from the "About..." window by mouse click

**Comment by FelixdelasPozas** [comment]
Thanks for noticing it! Fixed in the [latest release](https://github.com/FelixdelasPozas/TrayWeather/releases/tag/1.4.4).
Merry christmas!

Regards,
Félix.

**Comment by adem4ik** [comment]
Fixed, thanks. Happy Holidays!
