### ISSUE TITLE
Invalid API Key

### ISSUE THREAD

**Issue by fabiomb** [FelixdelasPozas/TrayWeather#153]
When installing with an API Key the app can´t connect
it says "Invalid OpenWeatherMap API Key" the description says: "Host requires authentication"

the API is valid, I just created a new one, but the message "Host requires authentication" sounds like it needs something extra

**Comment by FelixdelasPozas** [comment]
Hi @fabiomb .

Look at the note [in the page](https://github.com/FelixdelasPozas/TrayWeather):

> **NOTE:** Please note that after you register in OpenWeatherMap and are given an API key, that key may not be valid right away. If you enter the API key in TrayWeather and get an "host requires authentication" error, you must wait a little longer until it becomes valid.

Wait for an hour or two until the key becomes valid.

Regards,
Félix.

**Comment by fabiomb** [comment]
gracias Felix!
