### ISSUE TITLE
Suggestion: more intuitive manual location selection

### ISSUE THREAD

**Issue by ryan-preble** [FelixdelasPozas/TrayWeather#156]
It would be nice if the user could search for a municipality or region for manual location selection rather than geographic coordinates. It can get a little annoying googling coordinates every time I want the app to display information for a different location. I could use the IP coordinates feature, except I always run a VPN, and it does not work with that. You might imagine a local database of city:coordinate pairs that can be used to query the OpenWeather servers, shouldn't take up too much space.

**Comment by FelixdelasPozas** [comment]
Hi @ryan-preble . 

I'll try to incorporate the [OpenWeatherMap geocoding](https://openweathermap.org/api/geocoding-api) as a third option of specifying the location for the next version. I can't say however when will that happen as I don't have much free time lately. 

Regards, 
Félix.

**Comment by FelixdelasPozas** [comment]
Hi @ryan-preble. 

The version 1.29 has been released with the dialog to get the coordinates of a location by name. You can find it [here](https://github.com/FelixdelasPozas/TrayWeather/releases/tag/1.29.0).

Regards,
Félix.
