### ISSUE TITLE
Help with translations for version 1.29.

### ISSUE THREAD

**Issue by FelixdelasPozas** [FelixdelasPozas/TrayWeather#158]
Hello @adem4ik , @autergame, @datenshi888, @cthulkhu and @zyh941.

I hope you are all doing fine. For the next release a new dialog has been added to search for the coordinates of a location by entering the name, and a new icon set has been added. 

The new texts that needs translations are in bold (the text in parentheses are my comments):

* **Public IP Address API provided by**
* **Find location...**
* **Search location coordinates**
* **Enter the city name and, optionally, the state code (only for the US) and country code divided by comma. Use 'ISO 3166 country codes'. For example: "London, GB"** (the text 'ISO 3166 is the link text'. Feel free to change the city of the example by one of your country).
* **Location:**
* **Enter location...**
* **Search**
* **Search results:**
* **Invalid reply from server. Couldn't get location information. If you have a firewall change the configuration to allow this program to access the network.**
* **No locations found for '%1'.**
* **Location finder**
* **No translation**
* **Local name**
* **State/Province/Region**

Thank you very much!
Regards,
Félix.

**Comment by adem4ik** [comment]
Hello. Russian translation is here:

- API публичных IP-адресов предоставлен
- Найти местоположение...
- Поиск координат местоположения
- Введите название города и, по желанию, код штата (только для США) и код страны через запятую. Используйте «коды стран ИСО 3166». Например: «Moscow, RU»
- Местоположение:
- Введите местоположение…
- Поиск
- Результаты поиска:
- Неверный ответ от сервера. Не удалось получить сведения о местоположении. Если у вас установлен сетевой экран, настройте его так, чтобы разрешить этой программе доступ к сети.
- Не найдено местоположение для «%1».
- Поиск местоположения
- Нет перевода
- Местное название
- Область/штат/провинция

I'm not sure if `City, Country` example should be translated or not. So I've left it in English.

**Comment by zyh941** [comment]
Hello. Simple Chinese as below:

- 公共 IP 地址 API 提供者是
- 查找位置...
- 搜索位置坐标
- 以逗号分隔，输入城市名称以及可选的州代码（仅适用于美国）和国家/地区代码。 使用“ISO 3166 国家/地区代码”。 例如：“London, GB”
- 地点：
- 输入位置...
- 搜索
- 搜索结果：
- 来自服务器的无效回复。 无法获取位置信息。 如果您有防火墙，请更改配置以允许本程序访问网络。
- 找不到“%1”的位置。
- 位置查找器
- 没有翻译
- 本地名称
- 州/省/地区

By the way, please change the translation of the last update (1.28.0):

- "knots"  “节”
- “kts” (abbreviation of knots)  “kts” (节的缩写)

**Comment by autergame** [comment]
Hello, Portuguese translation

- Endereço de IP público da API providenciado por
- Encontrar localização...
- Pesquisar coordenadas de localização
- Insira o nome da cidade e, opcionalmente, o código do estado (somente para os EUA) e o código do país dividido por vírgula. Use 'códigos de país ISO 3166'. Por exemplo: "London, GB"
- Localização:
- Insira o local...
- Procurar
- Procurar resultados:
- Resposta inválida do servidor. Não foi possível obter informações de localização. Se você tiver um firewall, altere a configuração para permitir que este programa acesse a rede.
- Nenhum local encontrado para '%1'.
- Localizador de localização
- Sem tradução
- Nome local
- Estado/Província/Região

**Comment by cthulkhu** [comment]
>     * **Public IP Address API provided by**
* **API публічних IP-адрес надано**

>     * **Find location...**
* **Знайти місцезнаходження...**

>     * **Search location coordinates**
* **Шукати координати місцезнаходження**

>     * **Enter the city name and, optionally, the state code (only for the US) and country code divided by comma. Use 'ISO 3166 country codes'. For example: "London, GB"**
* **Введіть назву міста, код штату (за бажанням, лише для США) та код страни через кому. Використовуйте [коди стран ISO 3166](https://www.iso.org/obp/ui/#search). Наприклад: "Kyiv, UA"**

>     * **Location:**
* **Місцезнаходження:**

>     * **Enter location...**
* **Введіть місцезнаходження...**

>     * **Search**
* **Пошук**

>     * **Search results:**
* **Результати пошуку:**

>     * **Invalid reply from server. Couldn't get location information. If you have a firewall change the configuration to allow this program to access the network.**
* ** Невірна відповідь від сервера. Не вдалося отримати інформацію про місцезнаходження. Якщо ви користуєтесь мережевим екраном, змініть його налаштування, щоб дозволити цій програмі мережевий доступ.**

>     * **No locations found for '%1'.**
> 
>     * **Location finder**
> 
>     * **No translation**
> 
>     * **Local name**
> 
>     * **State/Province/Region**

```

**Comment by cthulkhu** [comment]
* **Public IP Address API provided by**
>     API публічних IP-адрес надано

* **Find location...**
>     Знайти місцезнаходження...

* **Search location coordinates**
>     Шукати координати місцезнаходження

* **Enter the city name and, optionally, the state code (only for the US) and country code divided by comma. Use 'ISO 3166 country codes'. For example: "London, GB"**
>     Введіть назву міста, код штату (за бажанням, лише для США) та код страни через кому. Використовуйте 'коди стран ISO 3166'. Наприклад: "Kyiv, UA"

* **Location:**
>     Місцезнаходження:

* **Enter location...**
>     Введіть місцезнаходження...

* **Search**
>     Пошук

* **Search results:**
>     Результати пошуку:

* **Invalid reply from server. Couldn't get location information. If you have a firewall change the configuration to allow this program to access the network.**
>     Невірна відповідь від сервера. Не вдалося отримати інформацію про місцезнаходження. Якщо ви користуєтесь мережевим екраном, змініть його налаштування, щоб дозволити цій програмі мережевий доступ.

* **No locations found for '%1'.**
>     Немає місцезнаходжень для '%1'.

* **Location finder**
>     Пошук місцезнаходження

* **No translation**
>     Немає перекладу

* **Local name**
>     Місцева назва

* **State/Province/Region**
>     Штат/провінція/регіон

**Comment by datenshi888** [comment]
Slovenian translation:

- API za javni IP naslov zagotavlja
- Poiščite lokacijo...
- Poiščite koordinate lokacije
- Vnesite ime mesta in po želji kodo zvezne države (samo za ZDA) in kodo države, ločeno z vejico. Uporabite standard 'ISO 3166' za kodo države. Na primer: Ljubljana, SI
- Lokacija:
- Vnesite lokacijo...
- Iskanje
- Rezultati iskanja:
- Neveljavni odgovor strežnika. Informacij o lokaciji ni bilo mogoče pridobiti. Če imate požarni zid, spremenite konfiguracijo, da omogočite temu programu dostop do omrežja.
- Ni najdenih lokacij za '%1'.
- Iskalnik lokacije
- Brez prevoda
- Lokalno ime
- Zvezna država/Provinca/Regija

**Comment by FelixdelasPozas** [comment]
Hi. 

The new version is available [here](https://github.com/FelixdelasPozas/TrayWeather/releases/tag/1.29.0). Thank you all.

@zyh941 Regarding the additional translation of **knots**. The words in parenthesis are my comment, not part of the translation. Sorry if I didn't specify correctly. 

> By the way, please change the translation of the last update (1.28.0):
>  "knots" “节”
>  “kts” (abbreviation of knots) “kts” (节的缩写)

If the word **knots** in you language is just one character in length I suppose its better to use the word instead of any abbreviation and I've done like that in the application. If it's incorrect tell me and I will revert the changes. 

I'll close the issue but you can still write if needed.

Regards and thank you, 
Félix.
