### ISSUE TITLE
Program reverts to verison 16 after reboot.

### ISSUE THREAD

**Issue by partwaysane** [FelixdelasPozas/TrayWeather#159]
Have had this problem for a few months.  I update the program to the most recent version but, when I have to reboot my system, the program reverts to version 1.26.1.  Every time.  Thought with the update to 1.29 that it wouldn't happen again, but it does.

**Comment by adem4ik** [comment]
Sounds like you have 2 different installations of TrayWeather.

**Comment by partwaysane** [comment]
Thank you for getting back to me.  You were right.  I had two different
installations of TW on my computer.  Deleted the older one and it seems to
be working fine!  Thanks for your help.

**Comment by FelixdelasPozas** [comment]
I'll close as fixed them. Thanks to @adem4ik !!
