### ISSUE TITLE
Air pollution data

### ISSUE THREAD

**Issue by anonimuos** [FelixdelasPozas/TrayWeather#16]
Firstly, thank you for a very useful app :)

Please please please add air pollution data to your app. Air pollution is very high in my area and I need to see this data.

According to https://openweathermap.org/price, air pollution API is free. I can get it with this call:

http://api.openweathermap.org/data/2.5/air_pollution?lat={lat}&lon={lon}&appid={API key}

Also, please add an option to show relevant data in the tray icon as per season. e.g. in summer, I need to see temperature. In monsoon/rainy season, I need to see humidity. In winter, I need to see the air pollution data e.g. pm2_5 or pm10.

In web browser I am able to get it but it would be very useful to see in the app, the parameters like NO2, O3, SO2, PM2_5, PM10, NH3.

Also the temperature shown currently is just a number. Please add units after it in the tray e.g. °C or °F because I have several other indicators running in the tray e.g. Battery life of laptop, so it's hard to know what that figure is.

**Comment by FelixdelasPozas** [comment]
Hello.

The pollution data seems interesting. A chart with pollution forecast definitely can be useful. 

About showing units in the tray the answer is definitely a no. The area in the tray is very small, a temperature like "-10" already shows very small, trying to show "-10ºC" or "100ºF" will be unreadable. Same goes for showing "µg/m<sup>3</sup>". As for showing information other than temperature in the tray the concept is the same, how are we going to show "300.4 µg/m<sup>3</sup>" ? The idea is to omit the information we already know, like the units, because there is not enough area to make it readable and use shape and color to convey as much information as we can. The main interest in weather is the temperature, so changing it can be confusing.

I think the tray configuration options allow enough modifications to differentiate it from other applications.  Sometimes I use a CPU temp monitor at the same time and have no problem to distinguish what is what. 

I'll look at the pollution forecast in the next hours. Should be easy to add.

Regards, 
Félix.

**Comment by FelixdelasPozas** [comment]
The [latest release](https://github.com/FelixdelasPozas/TrayWeather/releases/tag/1.5.0) has a tab with pollution forecast information. Give it a try. 

![pollution](https://user-images.githubusercontent.com/12167134/104073647-83d92d00-520e-11eb-8b6c-901976f2429b.png)

Regards and happy new year!
Félix.

**Comment by anonimuos** [comment]
Thank you very very much for adding the air quality data. It is neat!

I feel that for the temperature, there's at least room for one tiny degrees symbol even if 'C' or 'F' is not added. -100° does not take much space vs -100 😊. Also, these days, we can easily control the padding around the tray (notification area) icons with 7+ Taskbar Tweaker. We can set it to e.g. tray_icons_padding=4 so the icons aren't as widely spaced out.

But seeing just a bunch of numbers is sometimes difficult to remember. A tiny ° symbol will make it so much easier. You can omit the C or F. In my tray, I have CPU temp, GPU temp, CPU clock speed, power (wattage) and battery life and air temperature (so 3 temps).

Also where I stay (Mumbai, India), the temperature is pretty much constant throughout the year - in the range of 27-32°C. So it is not very useful to see that same value in the tray. But humidity varies wildly in the monsoon months e.g. from March to Oct when it is upwards of 70-80% but falls to 30% in winter.

Similarly, in winter, the most important parameter becomes air quality index as India is one of the most polluted countries in the world in winter. AQI here is a simple value derived here mostly from PM10. So it would make TrayWeather a most useful app if I could switch via right click from the tray to show either the Temperature, Max temp, Humidity, or PM10. India is largely a country with very hot weather throughout the year except winter for short period of 2 months.

Also I feel the PM10 should be shown on the "Current Weather" tab as it largely reflects the overall Air Quality Index which the Govt uses. In fact in polluted countries, AQI is more important than when Sunrise/Sunset occurred, or Ground pressure. 😊 AQI is what we want to quickly check before heading out with a mask.

Please consider these requests. Microsoft themselves is planning to add certain weather data right in the tray area and as you can see from the screenshot, ( https://twitter.com/JenMsft/status/1347275815168327681 ), they are using a fair amount of space to show it but still, it is very useful to see at-a-glance info that matters the most to the user depending on the season of the year. (In certain places, temperature is far less important).

**Comment by FelixdelasPozas** [comment]
> I feel that for the temperature, there's at least room for one tiny degrees symbol even if 'C' or 'F' is not added. -100° does not take much space vs -100 blush. Also, these days, we can easily control the padding around the tray (notification area) icons with 7+ Taskbar Tweaker. We can set it to e.g. tray_icons_padding=4 so the icons aren't as widely spaced out.
> But seeing just a bunch of numbers is sometimes difficult to remember. A tiny ° symbol will make it so much easier. You can omit the C or F. In my tray, I have CPU temp, GPU temp, CPU clock speed, power (wattage) and battery life and air temperature (so 3 temps).

The tray icon can be configured to look different to the rest of tray icons and, also, the position can be moved in the tray area. I think there is very low probability of being confused even if you have other meters, with or without other tweaks. Often I use OpenHardwareMonitor and never had any problem. Adding another character to the tray text will make it smaller without adding any information. 

> Also where I stay (Mumbai, India), the temperature is pretty much constant throughout the year - in the range of 27-32°C. So it is not very useful to see that same value in the tray. But humidity varies wildly in the monsoon months e.g. from March to Oct when it is upwards of 70-80% but falls to 30% in winter.
> Similarly, in winter, the most important parameter becomes air quality index as India is one of the most polluted countries in the world in winter. AQI here is a simple value derived here mostly from PM10. So it would make TrayWeather a most useful app if I could switch via right click from the tray to show either the Temperature, Max temp, Humidity, or PM10. India is largely a country with very hot weather throughout the year except winter for short period of 2 months.
> Also I feel the PM10 should be shown on the "Current Weather" tab as it largely reflects the overall Air Quality Index which the Govt uses. In fact in polluted countries, AQI is more important than when Sunrise/Sunset occurred, or Ground pressure. blush AQI is what we want to quickly check before heading out with a mask.

While I think that I must try to accommodate every user, I know is impossible to cover every need of every user at the same time. The things you've mentioned are particular to your area and I think that they do not justify changing the application. The intention of the application is that you have all those information in a click away and the tray icon is intended for having a glimpse of current weather conditions, the temperature being the information the most people want. Trying to "cram" as much information as possible in the tray doesn't make much sense, it's not it's function. 
Currently I'm not planning on changing it, but if other people request similar things I'll reconsider. 

> Please consider these requests. Microsoft themselves is planning to add certain weather data right in the tray area and as you can see from the screenshot, ( https://twitter.com/JenMsft/status/1347275815168327681 ), they are using a fair amount of space to show it but still, it is very useful to see at-a-glance info that matters the most to the user depending on the season of the year. (In certain places, temperature is far less important).

Apparently it requires you to install the Chromium version of Microsoft Edge browser. I don't know why but.. ouch! I think I'll stay with mine. :grinning:
