### ISSUE TITLE
Columns inside search location window aren't translated

### ISSUE THREAD

**Issue by adem4ik** [FelixdelasPozas/TrayWeather#160]
Version: 1.29.0

1) Switch language from to English to Russian, Ukrainian, Simple Chinese, etc.
2) Open Configuration > Find Location

**Result:** `Location, Location name, Latitude, Longitude, Country, State/Province/Region` columns doesn't have translations.

![изображение](https://github.com/FelixdelasPozas/TrayWeather/assets/4707112/7fb4ab59-4588-4357-843f-e4cf62c85930)
![изображение](https://github.com/FelixdelasPozas/TrayWeather/assets/4707112/50aac5c5-42a5-469b-8f7e-14cd64bf7436)

**Comment by FelixdelasPozas** [comment]
Thanks! Fixed. Will be in the next release (hopefully later in the day).

Regards, 
Félix.
