### ISSUE TITLE
[Suggestion] Set WindowsArguments = dpiawareness= to 1

### ISSUE THREAD

**Issue by adem4ik** [FelixdelasPozas/TrayWeather#161]
Version: 1.29

There is qt.conf inside TW folder with:
```
[Platforms]
WindowsArguments = dpiawareness=0
```
It can be changed to the following to support custom DPI.
```
[Platforms]
WindowsArguments = dpiawareness=1
```

Here is comparison from my 2560x1440 resolution with 125% Windows scale enabled (0 vs 1).
![изображение](https://github.com/FelixdelasPozas/TrayWeather/assets/4707112/b4a1d061-ef45-4743-af19-a226591baec7)

It seems safe now as i can't reproduce [this issue](https://github.com/FelixdelasPozas/TrayWeather/issues/18). Here are the screens with 200% scale and `dpiawareness=1` :

![изображение](https://github.com/FelixdelasPozas/TrayWeather/assets/4707112/0a9a67cb-3f4f-4d0d-9cae-9890dc41e58a)
![изображение](https://github.com/FelixdelasPozas/TrayWeather/assets/4707112/9677c58f-f51f-44ea-a259-a953f72c730e)

**Comment by FelixdelasPozas** [comment]
If the old issue is fixed I'll set it as 

> [Platforms]
> WindowsArguments = dpiawareness=1

for the next releases. 

Regards, 
Félix.
