### ISSUE TITLE
Suggestion: add github link into "About" window

### ISSUE THREAD

**Issue by adem4ik** [FelixdelasPozas/TrayWeather#19]
**Version:** 1.5.3
- Open "About..." window

**Suggested result:** window has the following link - https://github.com/FelixdelasPozas/TrayWeather 

It would be useful to post issues or to check newer versions faster.
![image](https://user-images.githubusercontent.com/4707112/104427565-d1ea8980-559c-11eb-93fd-6940898ee41d.png)

**Comment by FelixdelasPozas** [comment]
Added a link in the release [1.5.4](https://github.com/FelixdelasPozas/TrayWeather/releases/tag/1.5.4). Thanks!
