### ISSUE TITLE
Feature request: Remember map options

### ISSUE THREAD

**Issue by treyturner** [FelixdelasPozas/TrayWeather#24]
Every time I click on the map, I am looking for the OpenStreetMap Rain map, but the map tab doesn't seem to remember which map or layer I last selected. It would be a nice feature if it remembered these selections. Thanks for your time!

**Comment by FelixdelasPozas** [comment]
Added in the [latest release 1.8.0](https://github.com/FelixdelasPozas/TrayWeather/releases/tag/1.8.0). Map layers configuration for both the street and weather layers will be saved and restored from now on.

Regards,
Félix.
