### ISSUE TITLE
Feature request: 10 day forecast

### ISSUE THREAD

**Issue by treyturner** [FelixdelasPozas/TrayWeather#25]
I would be very interested in a 10-day forecast tab that shows the high temperature, low temperature, chance of precipitation, and general forecast (sunny/(partly) cloudy/light showers/thunderstorms/etc) for the next 10 days. Attached is a screenshot of the 10 day forecast from weather.com that sets an excellent example. Thanks for your consideration!

![image](https://user-images.githubusercontent.com/1878152/121309910-5d581480-c8c8-11eb-9ce2-1156129005df.png)

**Comment by FelixdelasPozas** [comment]
TrayWeather uses the [free information](https://openweathermap.org/price) provided by OpenWeatherMaps, that is only 7 days forecast (at most). There is no workaround about that, as more detailed information will require another (non-free & expensive) plan.

Regards,
Félix.

**Comment by treyturner** [comment]
Ok, a 7-day forecast then? :) I'm less worried about the extra 3 days than I am the view that was captured above! Thanks for responding so quickly to my feature requests by the way, updating now!

**Comment by FelixdelasPozas** [comment]
I don't think that the graph is more difficult to read, in fact I believe it gives more information in a very compact way. It's true that you have to hover to get the exact measures, but that is to avoid multiple curves like in the pollution graph. Doing it in a list fashion I think it's worse.
About the percentage of precipitation I think that's very confusing. 20% light drizzle is not the same as 20% heavy rain, you're taking information away. What about 80% drizzle and 20% heavy rain the next day? You will only see 80% one day and 20% the next, I think it will give you the wrong information thinking the first day is gonna rain more (maybe in time, not in precipitation). Maybe in your example is talking about humidity and not precipitation?
I'm thinking in changing the graph to add the weather icon in the background, just like the pollution graph does with air quality (but that graph uses colors) but that will be for the next release, probably. Apart from that I don't think that changing the forecast tab is a good idea.

Regards,
Félix.
