### ISSUE TITLE
Feature request: Open specific tab on double-click

### ISSUE THREAD

**Issue by treyturner** [FelixdelasPozas/TrayWeather#26]
It would be lovely if you could choose a specific tab to open when double-clicking on the icon in the system tray. Thanks for your work on the app and your consideration of this feature request.

**Comment by FelixdelasPozas** [comment]
Added in the [latest release (1.8.0)](https://github.com/FelixdelasPozas/TrayWeather/releases/tag/1.8.0). From now on if no menu entry is selected in the context menu (that will override the tab to show) and the application is opened using a double click in the tray icon the last tab viewed will be shown. 

Regards,
Félix.
