### ISSUE TITLE
Feature request: Direct access to tabs from right-clicking icon

### ISSUE THREAD

**Issue by treyturner** [FelixdelasPozas/TrayWeather#27]
Hi again,
It would be a convenient feature to allow direct access to the various tabs of the forecast window by selecting them from the context menu shown by right-clicking the icon.

In other words, you could replace the 'Weather & forecast' menu option with direct links to Current Weather, Forecast, Pollution, and Maps. You could even break out the specific maps if desired for direct access from the system tray.

I promise this is my last feature request! If you have a Ko-fi account or a way that I could support development of your application I'd be more than happy to do so.

Thanks one last time for your work and consideration of this request.

**Comment by FelixdelasPozas** [comment]
Separated menu entries for the tabs can be useful but I don't think the same for maps. Added in the [1.8.0 release](https://github.com/FelixdelasPozas/TrayWeather/releases/tag/1.8.0).

![image](https://user-images.githubusercontent.com/12167134/121608218-c7e88c00-ca51-11eb-8501-9a45314cf2fc.png)

Regards,
Félix.
