### ISSUE TITLE
Configuration window is too tall and doesn't fit on the screen

### ISSUE THREAD

**Issue by tomasz1986** [FelixdelasPozas/TrayWeather#29]
The configuration window is too tall, and as such it doesn't fit on the screen. The bottom part is basically cut out and inaccessible. For instance, it barely fits on my 1920x1200 resolution monitor here, and it does not on anything smaller than that.

Would it be possible to implement some kind of a scrollbar to make all the settings accessible on smaller resolution screens?

**Comment by FelixdelasPozas** [comment]
I've modified the configuration dialog with tabs to be smaller, it will be in the next release. 

![Configuration_dark](https://user-images.githubusercontent.com/12167134/121784618-2f6b1c80-cbb5-11eb-83b8-c1182007a32c.png)
![Configuration_light](https://user-images.githubusercontent.com/12167134/121784619-3003b300-cbb5-11eb-949f-8f45ae26befb.png)

**Comment by FelixdelasPozas** [comment]
You can download the latest version with the smaller configuration dialog [here](https://github.com/FelixdelasPozas/TrayWeather/releases/tag/1.8.1).

Regards,
Félix.
