### ISSUE TITLE
Tray buttons settings are not saved

### ISSUE THREAD

**Issue by SamLab** [FelixdelasPozas/TrayWeather#30]
After PC reboot not saved "option to use two tray icons, one for the weather icon and other with the current temperature"

**Comment by FelixdelasPozas** [comment]
Hi, I've looked at the tray icon code and did some testing. Looks to be working fine for me. Could you give me more details about the problem? A more detailed description of what happens and what you think should happen instead? Witch Windows operating system are you using? Are the tray area settings allowing the tray weather icons to be show or is the OS hiding them?

Regards,
Félix.

**Comment by FelixdelasPozas** [comment]
I've changed a little the code of the additional tray icon in the [latest release 1.8.3](https://github.com/FelixdelasPozas/TrayWeather/releases/tag/1.8.3). Try it and check if your problem have been solved or changed. 

Regards,
Félix.

**Comment by SamLab** [comment]
> I've changed a little the code of the additional tray icon in the [latest release 1.8.3](https://github.com/FelixdelasPozas/TrayWeather/releases/tag/1.8.3). Try it and check if your problem have been solved or changed.
> 
> Regards,
> Félix.

The problem was on Windows 8.1 and 10 - on 8.1 the problem disappeared - on 10 I can check later

**Comment by SamLab** [comment]
Another problem on all windows - during installation, the installer cannot close the TrayWeather.exe process - you have to kill the process manually

**Comment by FelixdelasPozas** [comment]
> Another problem on all windows - during installation, the installer cannot close the TrayWeather.exe process - you have to kill the process manually

That is handled by a parameter in the installer script in [Inno Setup](https://jrsoftware.org/isinfo.php) called **'CloseApplications'**. Apparently in some WindowsOS has problems. In the next release I will change it from ```CloseApplications: yes``` to ```CloseApplications: force```. That's supposed to fix it. In my OS (Win7) seems to be working fine as it is. 

Regards,
Félix.

**Comment by SamLab** [comment]
Closing process issue resolved.
But in Windows 10, the tray icon settings are not saved - I make 2 icons, after rebooting only 1 remains - the temperature

**Comment by FelixdelasPozas** [comment]
I don't have a Win10 machine, so this will be difficult. First check that windows is not hiding the "missing icon" in the taskbar settings, because in Win7 tray icons of new applications are hidden by default. I will look into the code for saving/restoring the configuration to check if could be a problem in Win10. 

> Also, after a reboot, the specified icon size is also reset.

There is no icon size in the configuration, are you referring to "Temperature text size" or maybe "Icon type"?

Regards,
Félix.

**Comment by SamLab** [comment]
> I don't have a Win10 machine, so this will be difficult. First check that windows is not hiding the "missing icon" in the taskbar settings, because in Win7 tray icons of new applications are hidden by default. I will look into the code for saving/restoring the configuration to check if could be a problem in Win10.
> 
> > Also, after a reboot, the specified icon size is also reset.
> 
> There is no icon size in the configuration, are you referring to "Temperature text size" or maybe "Icon type"?
> 
> Regards,
> Félix.

"Temperature text size" - not saved all "Tray Icon" settings

**Comment by FelixdelasPozas** [comment]
I've reviewed the configuration code and tray options seems to be stored and updated correctly. The configuration is saved when exiting the application so maybe Win10 terminated the application instead of closing it when rebooting?
In [1.8.4](https://github.com/FelixdelasPozas/TrayWeather/releases/tag/1.8.4) I've changed a little the code in the configuration dialog but nothing related to this. If the problem persists in the next release I will change the code to save the configuration when the dialog closes too. 

Regards,
Félix.

**Comment by SamLab** [comment]
Both problems are active - during installation, the program does not close and after a reboot, the settings are reset

![Безымянный](https://user-images.githubusercontent.com/4008500/124375130-2dbee100-dca9-11eb-9fca-282c9c3a3e28.png)

**Comment by SamLab** [comment]
I simulated a situation when there is a problem and when it is not:
there is a problem - I change the program settings and reboot without closing the program
no problem - I change the settings, close the program, open the program again without touching the settings and reboot

**Comment by FelixdelasPozas** [comment]
In the [1.8.5](https://github.com/FelixdelasPozas/TrayWeather/releases/tag/1.8.5) release the application will now save the modified configuration after closing the Configuration dialog. For solving the problem of "not being saved when being rebooted" I've also changed the code related to that and now it does in a more generic way (when detecting the aboutToQuit signal) when exiting the application. Lets see if this fixes your problem. The rest of users shouldn't notice anything different, at least in my tests I didn't. 

Regards, 
Félix.

**Comment by SamLab** [comment]
Now the settings are saved!, But again TrayWeather.exe does not close when installing... 
![Безымянный](https://user-images.githubusercontent.com/4008500/124396480-7a8ad200-dd12-11eb-96ef-f4fd3a941fe3.png)

**Comment by FelixdelasPozas** [comment]
It seems that the "force" option in the installer didn't work... In the next release I will try another thing and I'll update the issue then to notify you. Thanks!

**Comment by FelixdelasPozas** [comment]
I've updated the installer, try the [new one](https://github.com/FelixdelasPozas/TrayWeather/releases/download/1.8.5/TrayWeather_v1.8.5_Setup.exe). It should close the application before updating the executable.

**Comment by FelixdelasPozas** [comment]
Check the [release 1.8.6](https://github.com/FelixdelasPozas/TrayWeather/releases/tag/1.8.6). I've tested in a Win10 machine and seems to work, closing the running application before installing. 

Regards,
Félix.

**Comment by SamLab** [comment]
yes - now everything works

ps - people on my forum write that it does not work for win 11, but I do not have it and cannot check

**Comment by FelixdelasPozas** [comment]
Great, I'll close the issue then. 

> ps - people on my forum write that it does not work for win 11, but I do not have it and cannot check

We'll cross that bridge when we get there, as Win11 hasn't been released yet.

Regards,
Félix.
