### ISSUE TITLE
1.8.3 A valid API key shows as invalid

### ISSUE THREAD

**Issue by einzruff** [FelixdelasPozas/TrayWeather#31]
Thanks for the app.
I downloaded the latest release, 1.8.3, and created an OpenWeatherMap account to get an API key. Upon entering it in the Configuration window and clicking "Test API Key" it said "Invalid OpenWeather API Key." with details showing "host requires authentication". 
I installed the next newest release, 1.8.2, and it took my API key this time. 
Just FYI on your current release.

**Comment by FelixdelasPozas** [comment]
In OpenWeatherMap site says that there is a brief time before the key is activated, so probably you tried to use it when it was still invalid. 
The code in configuration dialog that checks the key hasn't changed recently and neither has changed the code in the application that uses the key to retrieve weather data. Probably the key was activated while you were downloading and installing the 1.8.2 version. If you try the 1.8.3 version with your key I'm sure it will work. If not, update this issue with details about your OS, and if it works tell me to close the issue.

Regards, 
Félix.

**Comment by einzruff** [comment]
Ok, I can confirm 1.8.3 now works for me, so it must have been the lag time between signing up for the OpenWeatherMap account. I realize I should have looked at the closed Issues, because I do see a similar post in there now. Thank you.
