### ISSUE TITLE
APIs [Question]

### ISSUE THREAD

**Issue by smaragdus** [FelixdelasPozas/TrayWeather#32]
@FelixdelasPozas 

For years I had been using two free but not open source programs- [sWeather](https://www.dcmembers.com/skwire/download/sweather/) and [WeatherMate](http://ravib.com/wm/) (I preferred the former since it was lighter and provided more weather data) which were mostly reliable. But recently both programs stopped working and I sought for alternatives. I came upon your [Tray Weather](https://github.com/FelixdelasPozas/TrayWeather) and without reading the description and requirements I installed it only to find out that one needed to get an [API](https://openweathermap.org/appid) [key](https://home.openweathermap.org/users/sign_up) from [OpenWeatherMap](https://openweathermap.org/). After having a look at their [Privacy Policy](https://openweather.co.uk/privacy-policy) I decided that I didn't want their key and that Tray Weather was not for since I did not want to register just to be able to use a weather service. So I had to uninstall [Tray Weather](https://github.com/FelixdelasPozas/TrayWeather) without even being able to test it.

I would like to ask- have you explored other alternative APIs? Can these projects- [Bright Sky](https://github.com/jdemaeyer/brightsky) and [wttr.in](https://github.com/chubin/wttr.in), be of any use for your [Tray Weather](https://github.com/FelixdelasPozas/TrayWeather) program? For the time being I have to rely on web services like [wttr.in](https://wttr.in/) to get weather data which I find extremely awkward.

Regards

**Comment by FelixdelasPozas** [comment]
Hi @smaragdus . 

I'll be happy to use a completely free API that provides weather and maps data for the whole world, but I don't think that service exists. 

Weather data cost and someone has to pay for it in one way or another. [Bright Sky](https://github.com/jdemaeyer/brightsky) uses the free german weather data and it's focused only on Germany (I suppose the germans pay it with taxes, and some services are also paid). And [wttr.in](https://github.com/chubin/wttr.in) gets its data from [WorldWeatherOnline](https://www.worldweatheronline.com/developer/) and I suppose the developer is using one of the paid plans (Starter or Pro, probably, depending in the amount of API requests per day, that I don't know). Also wttr.in doesn't provide wind/temp/cloud/rain maps that [TrayWeather](https://github.com/FelixdelasPozas/TrayWeather) uses. Even my own country [privides](http://www.aemet.es/es/datos_abiertos/AEMET_OpenData) weather data but under _public prices_ given that _they are providing a service_, even if we are paying it with our taxes.

For myself I think that using the _free_ (not really free, they are gathering usage data and we don't really know the extent of what for) [OpenWeatherMap](https://openweathermap.org/) data its a compromise I am willing to accept. 

Right now TrayWeather uses OpenWeatherMap API, but I will be willing to change it if another free alternative appears that provides the same or more detailed information. 

Regards,
Félix.

**Comment by smaragdus** [comment]
@FelixdelasPozas 

Hello Felix,

Thank you for your quick, kind, helpful and detailed response. Actually I supposed that you had explored other alternatives but yet I wanted to ask you.  What you said is no surprise for me. Although that I am more and more convinced that there is no privacy once you connect to the internet and that the main purpose for the creation of the web was surveillance, tracking, profiling and data harvesting I still persist in my Quixotic behaviour to at least give as less data as possible to the global web data sharks. I suppose that in the future I might get a key from [OpenWeatherMap](https://openweathermap.org/) using disposable mail plus proxy/VPN.

If I have time I may also have a look at the open source Android weather apps and if it happens that I come upon something that might be useful for your project I will let you know.

Since you are serious and responsive developer and since you use one of the few programming languages that I really like from the perspective of a user- C++ (yes, I am not a programmer) I may also test some of your other programs, some of which look interesting to me. Once it was a hobby of mine to test software but recently I test less and less stuff. I think that I should warn you that after testing your programs I may suggest some possible enhancements.

Since this issue was just a question and since you responded thoroughly I will close it.

Best regards

**Comment by smaragdus** [comment]
@FelixdelasPozas 

Have you checked [this site](https://developer.yr.no/)? This is the [WeatherAPI documentation](https://docs.api.met.no/doc/).

**Comment by FelixdelasPozas** [comment]
Hi. Seems it gives very good predictions (hourly predictions for the first days and later every 6/12 hours, instead of the constant 3 hour interval of OWM) and doesn't need an API key (just a query with latitude and longitude and you're done). However it doesn't provide maps of any kind or pollution data so we will be losing features. 

Regards,
Félix.

**Comment by smaragdus** [comment]
@FelixdelasPozas 

Thanks for the quick response. One more question- have you thought of making [Tray Weather](https://github.com/FelixdelasPozas/TrayWeather) use multiple APIs so that the user might choose which one they prefer? I am sure this would require a lot of hard work but I also see that you are working constantly on your tool. About me, I don't need maps of any kind, and even less pollution maps. By the way I had a look at the main site- [Yr](https://www.yr.no/nb), and it works fine but it is in Norwegian (**Søk=Seek**).

Regards

**Comment by FelixdelasPozas** [comment]
I haven't seen any other service that provides (more or less) the same data provided by OpenWeatherMap. If I find something I like I might think about updating TW. But right now the answer is that there is no provider similar to OWM. Also, as you can see from the list of [free apis](https://github.com/public-apis/public-apis#weather) most of them require to register to get an "apiKey", and that's precisely what you don't want, right?

Regards,
Félix.

**Comment by smaragdus** [comment]
@FelixdelasPozas 

> Also, as you can see from the list of [free apis](https://github.com/public-apis/public-apis#weather) most of them require to register to get an "apiKey", and that's precisely what you don't want, right?

Yes, exactly. If it happens that I come upon a free API not present in [the list](https://github.com/public-apis/public-apis#weather) I will post it here.

¡Todo lo mejor!
