### ISSUE TITLE
Double clicking weather icon does not open window

### ISSUE THREAD

**Issue by enervated** [FelixdelasPozas/TrayWeather#33]
With Tray Weather 1.8.4, if "Weather icon & temperature icon" is set, double clicking the temperature icon opens the "Current Weather" / "Forecast" / "Pollution" / "Maps" window. However, double clicking the weather icon does not.

**Comment by FelixdelasPozas** [comment]
Yes, it's a bug. In the next release I fill fix it. Thanks!

Regards,
Félix.

**Comment by FelixdelasPozas** [comment]
Fixed in [1.8.5](https://github.com/FelixdelasPozas/TrayWeather/releases/tag/1.8.5).

Regards,
Félix.

**Comment by enervated** [comment]
Thank you!
