### ISSUE TITLE
Inconsistent temperature text sizing

### ISSUE THREAD

**Issue by enervated** [FelixdelasPozas/TrayWeather#34]
I set my "Temperature text size" to 290, but the text size grows and shrinks somewhat, seemingly randomly. I've taken a few screenshots of the text--all of the temperatures shown are with the text size set to 290. You can clearly see that "88" is relatively large and slightly cut off in the middle image, then appears smaller in the one below that. Those two temps appeared as I was gathering this info.

![2021-07-06_20-06-29](https://user-images.githubusercontent.com/11533799/125203056-b824b900-e244-11eb-9909-c822c9f016fc.png)

**Comment by FelixdelasPozas** [comment]
Fixed in the [latest release 1.8.6](https://github.com/FelixdelasPozas/TrayWeather/releases/tag/1.8.6). Thanks for noticing and reporting! Now it will be consistent but maybe you must adjust the size one last time. 

Regards,
Félix.

**Comment by enervated** [comment]
Thank you!
