### ISSUE TITLE
Small typo in the source language

### ISSUE THREAD

**Issue by adem4ik** [FelixdelasPozas/TrayWeather#38]
It seems like a typo here https://github.com/FelixdelasPozas/TrayWeather/blob/master/languages/empty.ts#L442 - extra dot at the start of the sentence:
 `.Couldn&apos;t get location information.`

**Comment by FelixdelasPozas** [comment]
Thanks! There were two instances of it. Fixed in [1.9.2](https://github.com/FelixdelasPozas/TrayWeather/releases/tag/1.9.2).

Regards,
Félix.
