### ISSUE TITLE
'dd (hh)' shouldn't be translatable

### ISSUE THREAD

**Issue by adem4ik** [FelixdelasPozas/TrayWeather#39]
I think following source string shouldn't be available for translation - https://github.com/FelixdelasPozas/TrayWeather/blob/master/languages/empty.ts#L967
`<source>dd (hh)</source>`

Unfortunately I've translated it in Russian and it broke date display in the Forecast tab:
![image](https://user-images.githubusercontent.com/4707112/126397291-16d85f0d-46e5-410c-9d61-883cfda1faa1.png)

P.S. I'll fix in ru_RU.ts with a new PR.

**Comment by FelixdelasPozas** [comment]
It's a coincidence that "Day (Hour)" is "Dia (Hora)" in Spanish, so "dd(hh)" is the same and in Spanish that doesn't happen, and then I didn't catch it. Thanks! It will be fixed in the next release. 

Regards,
Félix.

**Comment by FelixdelasPozas** [comment]
Fixed in [1.9.3](https://github.com/FelixdelasPozas/TrayWeather/releases/tag/1.9.3).

Regards,
Félix.
