### ISSUE TITLE
Crash after multiple clicks on 'Show/Hide maps' button

### ISSUE THREAD

**Issue by adem4ik** [FelixdelasPozas/TrayWeather#40]
Version: 1.9.2
Windows 10 x64
- Open 'Current weather'
- Click on 'Show/Hide maps' button
- Repeat multiple times

Result: message 'Maps couldn't be loaded' and the crash after it
Video: http://somup.com/criYrAY0rR

**Comment by FelixdelasPozas** [comment]
I've tried to make the showing/hiding maps tab more secure. Hopefully the next release should fix it. Thanks!

Regards,
Félix.

**Comment by FelixdelasPozas** [comment]
Try it in the [latest release 1.9.3](https://github.com/FelixdelasPozas/TrayWeather/releases/tag/1.9.3). I couldn't reproduce the problem so its an attempt to fix it. Although if not, I wouldn't try further as its cause it's something not many users will try.

Regards,
Félix.

**Comment by adem4ik** [comment]
Fixed in 1.9.3: http://somup.com/cri3hbYTIb
