### ISSUE TITLE
Settings get reset after changing language

### ISSUE THREAD

**Issue by adem4ik** [FelixdelasPozas/TrayWeather#43]
Version 1.9.2
Windows 10 x64

- Open Configuration window
- Change 'Icon type' or 'Visual theme' & apply by OK
- Open Configuration once more & change language

Result: 'Icon type'/'Visual theme' get reset
Video: http://somup.com/criroPYZtd

**Comment by FelixdelasPozas** [comment]
Yep, Qt resets the dialog when a new translation is selected, some data has to be restored. Will fix it in the next release. Thanks.

Regards,
Félix.

**Comment by FelixdelasPozas** [comment]
Test it in [latest version 1.9.3](https://github.com/FelixdelasPozas/TrayWeather/releases/tag/1.9.3). I think it's fixed now. I'll close the issue when verified it works.

Regards,
Félix.

**Comment by adem4ik** [comment]
Works in 1.9.3: http://somup.com/cri3hDYTII
