### ISSUE TITLE
Forecast popup has cropped text in Russian

### ISSUE THREAD

**Issue by adem4ik** [FelixdelasPozas/TrayWeather#46]
Version 1.9.3
Windows 10 x64

- Switch to Russian
- Open Forecast
- Hover the cursor over the graph

Result: some units/digits can be cropped

I guess popup has static size and it doesn't stretch depending of the content.

![image](https://user-images.githubusercontent.com/4707112/126679911-adea5567-c648-40df-97c9-3f88a6d15375.png)

**Comment by FelixdelasPozas** [comment]
Thanks, Also the icon wasn't completely centered in the weather tooltip. I fixed it and will be in the next release. I'll leave this open until then.

Regards,
Félix.

**Comment by FelixdelasPozas** [comment]
The code of the tooltip widgets have been reworked a to ensure that they are the smallest size possible while not cropping the text. Try the [1.10.0 release](https://github.com/FelixdelasPozas/TrayWeather/releases/tag/1.10.0).

Regards,
Félix.

**Comment by adem4ik** [comment]
Fixed now, thanks!
![image](https://user-images.githubusercontent.com/4707112/127051194-265d605a-f9dc-4e1c-898f-6983c1973b42.png)
