### ISSUE TITLE
Update Russian translation.

### ISSUE THREAD

**Issue by FelixdelasPozas** [FelixdelasPozas/TrayWeather#48]
@adem4ik 

The next release will include a ultraviolet radiation chart, and some texts needs translations for the Russian language. The texts are:
```
- UV...
- Low
- No protection required.
- Moderate
- Protection required.
- High
- Very high
- Extra Protection. Avoid being ouside during midday hours.
- Extreme
- Current ultraviolet radiation index.
- Ultraviolet radiation.
- UV index
- Ultraviolet radiation forecast for the next days.
- UV
- UV Index
```

I was looking at the OneCall API from OWM and while the OneCall API provides the benefit of getting more information in less calls, it just provides detailed forecast (1 hour interval) for the next 24 hours and the next days are in 6 hour intervals. It's preferred to have the current forecast (3 hours interval). The UV index chart will allow me to maintain the code for the OneCall API in case the old API becomes deprecated.
This will be in the 1.10.0 release.

Regards,
Félix.

**Comment by adem4ik** [comment]
Hi, here is the translation
```
- УФ...
- Низкий
- Защита не требуется.
- Умеренный
- Требуется защита.
- Высокий
- Очень высокий
- Требуется дополнительная защита. Старайтесь не выходить на улицу в полдень.
- Экстремальный
- Текущий индекс ультрафиолетового излучения.
- Ультрафиолетовое излучение.
- УФ-индекс
- Прогноз ультрафиолетового излучения на ближайшие дни.
- УФ
- УФ-индекс
```

**Comment by FelixdelasPozas** [comment]
Many thanks! Updated and [released](https://github.com/FelixdelasPozas/TrayWeather/releases/tag/1.10.0).

Regards,
Félix.
