### ISSUE TITLE
Cannot Save "Check for Updates" Configuration Change

### ISSUE THREAD

**Issue by WCityMike** [FelixdelasPozas/TrayWeather#49]
Description:
I cannot save a configuration change; upon hitting OK, the button does not depress, the window disappears instantly, and upon going back to the configuration window, the changes were not made.

Steps to Reproduce:
1. Install TrayWeather.
2. Right click on the tray icon and pick "Configuration."
3. Click on "Visuals & Misc." tab.
4. Change "Check for Updates" to "Never."
5. Click on the "OK" button.

Expected action:
Button depresses and 'check for updates' change is registered as a configuration change.

Actual action:
If the configuration is checked (by repeating steps 2-3 above), the configuration change is not registered.

**Comment by FelixdelasPozas** [comment]
Hi. Fixed it, it won't happen in the next release. Thanks for noticing. I'll leave the issue open until release of the fixed version.

Regards,
Félix.

**Comment by FelixdelasPozas** [comment]
Fixed in [1.10.0](https://github.com/FelixdelasPozas/TrayWeather/releases/tag/1.10.0). Because this bug _everyone_ was doing weekly checkups... oopsie. Thanks.

Regards,
Félix.
