### ISSUE TITLE
Map legend only shows Celsius as temp range / and: mm or km on overlays

### ISSUE THREAD

**Issue by humantex** [FelixdelasPozas/TrayWeather#51]
Choosing Celsius or Fahrenheit as a configuration change to temperature display doesn't affect the legend overlay on the maps tab for temperature. It will only display Celsius. I'd assume that the temp overlay would at least change to show a Fahrenheit range.

The units for map distance will only show as "km", and switching to the 'Rain' overlay, it always shows the range as "mm", and not "in".

It might be more helpful to modify the configuration setting for "Temperature units" to "Measurement Units" to allow for a selection of either Imperial or Metric as the overall measurement units, and toggle all of the overlay legends markings and values to fit that choice.

![TrayWeather-Settings](https://user-images.githubusercontent.com/16087649/127370432-300e6dc7-e2e0-4ad4-96ff-98dc63e15753.jpg)

**Comment by FelixdelasPozas** [comment]
Hi @humantex . Yes, initially the maps are in the units provided by [OpenWeatherMaps layers](https://openweathermap.org/api/weather-map-2#layers) and needs translation for the palette values to other units. I've only translated the different maps titles (Temperature, Rain, etc). 

> It might be more helpful to modify the configuration setting for "Temperature units" to "Measurement Units" to allow for a selection of either Imperial or Metric as the overall measurement units, and toggle all of the overlay legends markings and values to fit that choice.

The plan to change it it's already in the [TODO list](https://github.com/FelixdelasPozas/TrayWeather/wiki). I'll probably do it while on vacations, still a week or two away from today. I'll leave the issue open and update it when I release a version with the units conversions.

Regards,
Félix.

**Comment by FelixdelasPozas** [comment]
Try the [latest release 1.11](https://github.com/FelixdelasPozas/TrayWeather/releases/tag/1.11.0), the maps should translate correctly with imperial units (inch/miles) including the "scale" widget. 
I'll close the issue now, if there is a translation problem or anything please open another issue. 

Regards,
Félix.
