### ISSUE TITLE
A more granular range of metric/non-metric options?

### ISSUE THREAD

**Issue by umbellipher** [FelixdelasPozas/TrayWeather#56]
I want temperature in C, not F. But wind in metres/sec just does not appear natural to me. Could we have temperature, pressure, wind, precipitation broken down into discrete options, so that one can opt for, say:

temp: C or F
pressure: hPA or PSI
wind: 3 options: metres/sec, or miles/hr, or km/hr
precipitation: none here at the moment, so I can't see the current options, but I guess mm or inches would be the options?

All of them separate, so one can mix and match.

Is that possible?

**Comment by FelixdelasPozas** [comment]
Hi @umbellipher . 

Working on it, it will be in the next release. 

Regards,
Félix.

**Comment by FelixdelasPozas** [comment]
Added in [version 1.12](https://github.com/FelixdelasPozas/TrayWeather/releases/tag/1.12.0).

Regards,
Félix.
