### ISSUE TITLE
Different weather icons

### ISSUE THREAD

**Issue by alystair** [FelixdelasPozas/TrayWeather#57]
I'm one of the folks that moved over from sWeather. Just curious how much of a pain it would be to allow different weather icons?

**Comment by FelixdelasPozas** [comment]
Hi @alystair. 

It's not difficult to add something like "icon themes". An icon theme needs only to comply with the following rules:
- Can be used for free (attribution will be given as always).
- Provide icons for all the [OpenWeatherMap codes](https://openweathermap.org/weather-conditions).
- Are SVG (to avoid scaling bitmaps, that avoids blurry images).

Preferably the icons must not provide from different sources so the style and colors are more or less the same.

Regards,
Félix.

**Comment by alystair** [comment]
No longer have the time to deal with this, sorry.
