### ISSUE TITLE
Error returning from sleep mode

### ISSUE THREAD

**Issue by alystair** [FelixdelasPozas/TrayWeather#58]
Application does not pull weather data successfully after resuming from a long sleep, works A-OK after refreshing by hand. Potentially delay query after waking up?

**Comment by FelixdelasPozas** [comment]
Hello @alystair.

The problem probably comes from disabling the Qt roaming polling of the network (a few versions ago to avoid network performance degradation) so when the computer wakes up doesn't know that the network has restarted also. The network polling is disabled when the "roaming mode" is disabled.
I've made a fix for the next release. I'll update the issue when it is released and leave it open until verifying that it has been solved.

Regards,
Félix.

**Comment by FelixdelasPozas** [comment]
Try the [1.12 release](https://github.com/FelixdelasPozas/TrayWeather/releases/tag/1.12.0), it should ask for new data immediately after detecting the "wake up" event. 

Regards,
Félix.

**Comment by alystair** [comment]
No issues so far, seems to have fixed it - thanks Felix!
