### ISSUE TITLE
Russian translation for 1.12

### ISSUE THREAD

**Issue by FelixdelasPozas** [FelixdelasPozas/TrayWeather#59]
Hi @adem4ik 

An update to the Russian translation is needed for version 1.12. The latest release will have a configuration tab to select measurement units. The texts are:

- Units
- Custom
- Custom Measurement Units
- Celsius
- Fahrenheit
- mmHg
- inHg
- meters/second
- kilometers/hour
- feet/second
- Precipitation
- millimeters
- feet/s
- km/h
- feet/sec

Thanks in advance!

Regards,
Félix.

**Comment by adem4ik** [comment]
Hi, 

- Units = Единицы
- Custom = Пользовательские
- Custom Measurement Units = Пользовательские единицы измерения
- Celsius = Градус Цельсия
- Fahrenheit = Градус Фаренгейта
- mmHg = мм рт. ст.
- inHg = дюйм рт. ст.
- meters/second = метр в секунду
- kilometers/hour = километр в секунду
- feet/second = фут в секунду
- Precipitation = Осадки
- millimeters = миллиметры
- feet/s = фут/c
- km/h = км/ч
- feet/sec = фут/с

**Comment by FelixdelasPozas** [comment]
Many thanks!

Regards,
Félix
