### ISSUE TITLE
Error when testing API KEY - Host requires authentication

### ISSUE THREAD

**Issue by ceduliocezar** [FelixdelasPozas/TrayWeather#6]
A message keeps showing on the screen, telling that: "Host requires authentication"

**Comment by ceduliocezar** [comment]
If I leave the valid API KEY there and input the latitude and longitude manually then hit OK, it simply says that its not possible to continue and closes the application after dismissing the dialog.

**Comment by FelixdelasPozas** [comment]
Apparently latitude range allowed numbers from -180 to 180. [New version 1.3.1](https://github.com/FelixdelasPozas/TrayWeather/releases/tag/1.3.1) fixes that to only allow numbers from -90 to 90. 

I'll leave this open but I will close it tomorrow supposing that it was only a mistake entering location data into configuration dialog if there is no answer. Thanks to ceduliocezar for spotting the error.

**Comment by FelixdelasPozas** [comment]
Try the [latest release](https://github.com/FelixdelasPozas/TrayWeather/releases/tag/1.3.2) and tell me if it fixes your problem.

**Comment by ceduliocezar** [comment]
It is working for me =)

Thanks

**Comment by michaelmuselik** [comment]
I have the same error
![image](https://github.com/FelixdelasPozas/TrayWeather/assets/73330785/d030d6ba-d302-4610-b593-2051c5c4ba2d)
W11, TW: TrayWeather_v1.26.1_Portable.7z
