### ISSUE TITLE
Geolocation failing 

### ISSUE THREAD

**Issue by blabes** [FelixdelasPozas/TrayWeather#7]
Getting the attached error when trying to test Geo-Locator:

![image](https://user-images.githubusercontent.com/8728493/67050350-e9b73180-f0fd-11e9-9383-93aff778c043.png)

Thinking this might be due to my ISP being rude enough to have a comma in the AS name (field 13) returned in the CSV by ip-api:
```
success,
United States,
US,
TX,
Texas,
Frisco,
75035,
33.1371,
-96.7488,
America/Chicago,
AT&T Internet Services,
,
"AS7018 AT&T Services, Inc.",
99.97.30.7
```
which is breaking your test [here](https://github.com/FelixdelasPozas/TrayWeather/blob/8f9d0665d10ab7ef9d853ef14e17b52bdb0e3a24/ConfigurationDialog.cpp#L203).

**Comment by FelixdelasPozas** [comment]
Yeah, the CSV parsing is very naive and doesn't handle values with commas. I will fix it during the weekend and make a release. Thanks for spotting this and sorry for the inconvenience. 
I'll close this when it's fixed.

**Comment by FelixdelasPozas** [comment]
The new release (1.3.4) should fix this problem. Please try it tell me if there's any other problem. Will close if resolved.

**Comment by blabes** [comment]
Success!  Thanks for the fix.

![image](https://user-images.githubusercontent.com/8728493/67213007-e2847200-f3e2-11e9-9c29-bbf941b43ca3.png)

Would you be interested in patches that would switch to using JSON for the ip-api calls, or not really?

**Comment by FelixdelasPozas** [comment]
Great. Really I have no preference, I guess I used CSV with ip-api because I already did JSON with OpenWheatherMap data, just to try something different. Now I know it has some caveats :)
For the moment I will keep it simple, thanks anyways. 
Close as resolved.

**Comment by blabes** [comment]
Sounds good... thanks again!
