### ISSUE TITLE
Update Chinese Simplified to 1.13.1

### ISSUE THREAD

**Issue by zyh941** [FelixdelasPozas/TrayWeather#71]
Hi Félix,
I found it has some mistakes in Chinese Simplified, so I just updated all of content in your empty translation document. Please fix it in your spare time, not urgent. lol
[Chinese Simplified 1.13.1.txt](https://github.com/FelixdelasPozas/TrayWeather/files/7696753/Chinese.Simplified.1.13.1.txt)

**Comment by FelixdelasPozas** [comment]
Hi @zyh941 . I've just released the version [1.13.2](https://github.com/FelixdelasPozas/TrayWeather/releases/tag/1.13.2) with your update. Thank you very much!

Regards,
Félix.
