### ISSUE TITLE
'translation' link doesn't work 

### ISSUE THREAD

**Issue by adem4ik** [FelixdelasPozas/TrayWeather#72]
Version: 1.13.2
OS: Windows 10 x64

- Open Configuration - Miscellaneous
- Click on the `translation` link

Result: nothing happens
Expected result: https://github.com/FelixdelasPozas/TrayWeather#translations

![image](https://user-images.githubusercontent.com/4707112/145821725-5060b3c0-5e54-4129-bfb6-23e1a476ef7d.png)

**Comment by FelixdelasPozas** [comment]
Fixed, will be in the next release. Thanks!

Regards, 
Félix.

**Comment by FelixdelasPozas** [comment]
Fixed in [version 1.14](https://github.com/FelixdelasPozas/TrayWeather/releases/tag/1.14.0).

Regards,
Félix.
