### ISSUE TITLE
[Suggestion] Dark graphs if the dark visual theme is enabled

### ISSUE THREAD

**Issue by adem4ik** [FelixdelasPozas/TrayWeather#73]
- Enable 'Dark' visual theme
- Open 'Maps...' - Forecast/Pollution/UV

Result: graphs look too light for the dark theme
Expected result: dark themed graphs

![2021-12-13_17-47](https://user-images.githubusercontent.com/4707112/145824412-3e0acf68-e124-4f1b-ad14-122a2aec2847.png)

![2021-12-13_17-47-inverted](https://user-images.githubusercontent.com/4707112/145824423-11714d0f-5fc0-4f64-8013-46eb57270730.png)

**Comment by FelixdelasPozas** [comment]
In the next release the graphs will use the theme colors.

**Comment by FelixdelasPozas** [comment]
The latest release, [version 1.14](https://github.com/FelixdelasPozas/TrayWeather/releases/tag/1.14.0), uses theme colors for the graphs.

Regards,
Félix.
