### ISSUE TITLE
Help with Russian translation for 1.14

### ISSUE THREAD

**Issue by FelixdelasPozas** [FelixdelasPozas/TrayWeather#74]
Hi @adem4ik .

For the next release the Russian translation needs to be updated with the following texts. 
* Weather:
* Sender:
* Start:
* Event:
* End:
* Description:
* Do not show this alert again.
* Show weather alerts
* Last alert...

Thanks!

**Comment by adem4ik** [comment]
Hi,

- Погода:
- Отправитель:
- Начало:
- Событие:
- Конец:
- Описание:
- Не показывать это оповещение снова.
- Показывать оповещения о погоде
- Последнее оповещение...

**Comment by FelixdelasPozas** [comment]
Many thanks. The [version 1.14](https://github.com/FelixdelasPozas/TrayWeather/releases/tag/1.14.0) with this update have been released.

Regards,
Félix.
