### ISSUE TITLE
Help with Chinese translation for 1.14

### ISSUE THREAD

**Issue by FelixdelasPozas** [FelixdelasPozas/TrayWeather#75]
Hi @zyh941

For the next release the Chinese translation needs to be updated with the following texts. 
* Weather:
* Sender:
* Start:
* Event:
* End:
* Description:
* Do not show this alert again.
* Show weather alerts
* Last alert...

Thanks!

**Comment by zyh941** [comment]
Hello Felix,
You can reference to these:
• Weather: 天气：
• Sender: 发送方：
• Start: 开始：
• Event: 事件：
• End: 结束：
• Description: 介绍：
• Do not show this alert again. 不要再显示此警告。
• Show weather alerts 展示天气警告
• Last alert... 最后的警告...

**Comment by FelixdelasPozas** [comment]
Many thanks. The [version 1.14](https://github.com/FelixdelasPozas/TrayWeather/releases/tag/1.14.0) with this update have been released.

Regards,
Félix.
