### ISSUE TITLE
'Invalid reply from Geo-locator server' after fast language changing in Configuration

### ISSUE THREAD

**Issue by adem4ik** [FelixdelasPozas/TrayWeather#78]
version: 1.14.0
OS: windows 10 x64

- Set Geographic location method to 'IP Geolocation'
- Open Configuration/Miscellaneous
- Perform fast language changing (select the field, use Up/Down keyboard arrows to switch languages)

Result: 'Invalid reply from Geo-locator server' dialog after 10-20 seconds of switching languages
![image](https://user-images.githubusercontent.com/4707112/146567837-bcb02d0c-1cce-4973-962e-d1f6b78be149.png)

I guess TW performs geo location request on every language change, so lots of language changes produce lots of requests. That's how IP Location status looks during the steps described above:
1. ![image](https://user-images.githubusercontent.com/4707112/146568771-643a1a7b-6d47-4447-8953-169d800111a4.png)
2. ![image](https://user-images.githubusercontent.com/4707112/146567723-6d79c5af-209a-4331-b980-885bd9e8e878.png)
3. ![image](https://user-images.githubusercontent.com/4707112/146567768-75cbe5b9-48ca-43a8-82b4-e23e2ca9bb5b.png)

**Comment by FelixdelasPozas** [comment]
Hi @adem4ik . I'll be fixed in the next release. 

Happy holidays.
Félix.

**Comment by FelixdelasPozas** [comment]
Fixed in [1.15](https://github.com/FelixdelasPozas/TrayWeather/releases/tag/1.15.0)

Regards,
Félix.

**Comment by adem4ik** [comment]
Thanks, fix is confirmed
