### ISSUE TITLE
Add temperature value in system try icon

### ISSUE THREAD

**Issue by hronek** [FelixdelasPozas/TrayWeather#8]
Please it is posible add to next version an option to show only value of temperature directly in system try icon? 
Because i see the weather from my widnowd but i want to know only the temperature. 
Of course you can add the temprature vaule to weather icon, it woould be better :)
Thx!!!

**Comment by FelixdelasPozas** [comment]
Hello. 

Initially I was against showing only the temperature in the tray icon, as I sometimes have a program that shows the temperature of the CPU in the same way and can be confusing if both are running. 
But I will look into it in a week or so, it can be made as an option. I think it will be better if both the weather icon and the temperature are shown at the same time. 
Also the temperature is shown in the icon tooltip.
![Clipboard01](https://user-images.githubusercontent.com/12167134/84885903-f5476780-b093-11ea-97aa-4a21fb32c282.png)

Regards,
Félix.

**Comment by hronek** [comment]
I know about tooltip, but I have to move the mouse down every time I want to know the temperature, instead of just looking. 
Yes, it would be good to make it optional, someone may not want it. 
Thank you very much for the adjusment and I look forward to it.

**Comment by FelixdelasPozas** [comment]
I just released version 1.4.0 with the option to see the temperature in the tray icon with several visualization options. Download the release from the [releases page](https://github.com/FelixdelasPozas/TrayWeather/releases) and give it a try. 

Regards,
Félix.

**Comment by hronek** [comment]
Thank you very much! You are awesome!

1.Maybe it wouldn't be bad to add more colors to the selection than just black and white - it wouldn't take much time?
2.When selecting "Weather icon & temperature", it would probably want a bold font to cover the weather image more, The temperature is very poorly seen.)

I apologize for the criticism. I just wanted to write my constructive comments. But of course it's fine as is. 
I use white color and I am are very happy :). 
Thank you once again!

**Comment by FelixdelasPozas** [comment]
Hi, go to the [releases page](https://github.com/FelixdelasPozas/TrayWeather/releases) and download the latest version. It will let you choose any color you want. And the font is bold. 
Maybe in the future the color can be changed from blue (cold) to red (hot) depending on the current temperature, just an idea. 

Regards, 
Félix.

**Comment by hronek** [comment]
Very well done. Thank you!
