### ISSUE TITLE
Help with Russian translation for 1.15

### ISSUE THREAD

**Issue by FelixdelasPozas** [FelixdelasPozas/TrayWeather#81]
Hi @adem4ik 

For the 1.15 release some new texts needs to be translated into Russian. The texts are:
* Icon Themes
* Selects the icon theme.
* Icon theme
* Changes icon theme color.
* Shows a summary of theme icons.

Thanks in advance.
Félix.

**Comment by adem4ik** [comment]
hello and happy new year:

- Темы значков
- Выбор темы значков.
- Тема значков
- Смена цвета темы значков.
- Отображение сводки по теме значков.

**Comment by FelixdelasPozas** [comment]
Version 1.15 [has been published](https://github.com/FelixdelasPozas/TrayWeather/releases/tag/1.15.0) with the updated translation, many thanks.

Best regards,
Félix.
