### ISSUE TITLE
Missing translation in 'Select color' dialog

### ISSUE THREAD

**Issue by adem4ik** [FelixdelasPozas/TrayWeather#83]
TW: 1.15.0

- Change language to something apart from English
- Open Configuration - Visuals
- Set 'Icon Theme' = `Flaticon Mono`
- Press button to change its color

Result: `Select color` dialog is in English translation
![image](https://user-images.githubusercontent.com/4707112/147833084-abc76dda-5e2e-4937-88e1-54b5811cd95b.png)

It looks like a standard dialog, so I guess it can use standard [qtbase](https://github.com/qt/qttranslations/tree/dev/translations) translations (i.e. `qtbase_ru.ts` for Russian).
![image](https://user-images.githubusercontent.com/4707112/147833256-2d8e1758-842f-42d2-a515-7f3b1cc2a9d7.png)

**Comment by FelixdelasPozas** [comment]
Yes, in fact is the same dialog used to select the colors of the temperature icon text (under 'text color'->'variable'). So I suppose it also happens there. I'll look into it in a few days. 
Thanks,
Félix.

**Comment by FelixdelasPozas** [comment]
Hi @adem4ik . This should be easy to solve for the next version. Thanks for noticing and reporting it.

Regards, 
Félix.

**Comment by FelixdelasPozas** [comment]
The [latest release](https://github.com/FelixdelasPozas/TrayWeather/releases/tag/1.16.0) 1.16 should use a translated version of the Qt default dialogs (if a Qt translation is available, that is). Try it out.

Regards, 
Félix.

**Comment by adem4ik** [comment]
@FelixdelasPozas Yes, it is mostly fixed now, thanks!
But it looks like Chinese Simplified is missing or `zh_CN`
![image](https://user-images.githubusercontent.com/4707112/148265855-359ea75b-0067-472f-8282-1fb69abaca4c.png)

**Comment by FelixdelasPozas** [comment]
Yes, the translations available are only for the languages in the Qt releases and as Qt has no default (at least in my release) translation for simplified chinese that is untranslated. I'll try one of the community ones for the next release, I have to test it before releasing.

Regards,
Félix.

**Comment by FelixdelasPozas** [comment]
Released a fix for Simplified Chinese in [1.16.1](https://github.com/FelixdelasPozas/TrayWeather/releases/tag/1.16.1).

Regards, 
Félix.

**Comment by adem4ik** [comment]
Great, thanks!
![image](https://user-images.githubusercontent.com/4707112/148290431-3abc9ca2-1ee2-4a16-a6b6-33952acf608e.png)

**Comment by FelixdelasPozas** [comment]
Solved in 1.16.1.
