### ISSUE TITLE
Unstable bottom border of the Configuration dialog

### ISSUE THREAD

**Issue by adem4ik** [FelixdelasPozas/TrayWeather#84]
TW: 1.15.0
Screen resolution: 1600x900 (native)
OS: Windows 10 x64

- Open Configuration - Location or Visuals tabs
- Move the window across the screen

Result: bottom border of the dialog is jumping
Video: https://user-images.githubusercontent.com/4707112/147834106-3bb644d8-d699-46c7-8279-0a378ed0d96e.mp4

**Comment by FelixdelasPozas** [comment]
Hi @adem4ik 

It's weird. After showing the dialog the size its "fixed" so it mustn't change size, or allow the user to change its size. May be a bug in Qt, I'll try to solve it.

Regards, 
Félix.

**Comment by FelixdelasPozas** [comment]
After checking a few things I think that must be a bug in Qt. Just modifying a bit the layout of the configuration dialog solved it for me. Check it in the [latest release 1.16](https://github.com/FelixdelasPozas/TrayWeather/releases/tag/1.16.0).

Regards, 
Félix.

**Comment by adem4ik** [comment]
Checked in 1.16.1:
- It seems to be fixed or at least less noticeable in the Light theme
https://user-images.githubusercontent.com/4707112/148547129-9ce57104-b217-4f40-9136-e1d594115e80.mp4

- But it is still the case for the Dark theme
https://user-images.githubusercontent.com/4707112/148547158-0b16a693-8d0c-430f-8893-cb3cad0dacd8.mp4

Well, if it's QT bug, feel free to close the issue

**Comment by FelixdelasPozas** [comment]
Nah, I'll tweak the dialog layout until I find the widget that is causing this problem and fix it. The Qt layout engine is probably resizing one widget when receiving an "update event" or a "paint event" in one of the tabs and causing this problem.

**Comment by FelixdelasPozas** [comment]
@adem4ik test the [release 1.16.2](https://github.com/FelixdelasPozas/TrayWeather/releases/tag/1.16.2). I tweaked the layout enough and right now I can't see the problem neither in light nor the dark themes. 

Regards, 
Félix.

**Comment by adem4ik** [comment]
@FelixdelasPozas This issue seems to be fixed in 1.16.2 for both dark/light themes. It is not reproduceable anymore on my side.
