### ISSUE TITLE
Tray icon location

### ISSUE THREAD

**Issue by iHastr** [FelixdelasPozas/TrayWeather#98]
Can you add an Option in Settings to have the temperature icon on the left and the weather icon on the right in the system tray? By default, the weather icon is on the left and the temperature icon is on the right. I'm more comfortable the other way around. So I have to drag the tray icons with the mouse.

**Comment by FelixdelasPozas** [comment]
Hi @iHastr .

I don't have control about where Windows places the icons (or even if it hides it if the user requests it), I can just create them and add to the toolbar. However I can swap the tray icons, so in a few days I'll look into it and, if that is a solution, maybe add an option in the Misc. tab of the Configuration Dialog to do so. 

Regards, 
Félix.

**Comment by FelixdelasPozas** [comment]
Sorry for the delay. I've tested it in Windows 7 and works fine. I suppose will also work well also in newer Windows versions. The new version will be released soon.

![Clipboard01](https://user-images.githubusercontent.com/12167134/159187658-39878f33-584a-4805-b47a-db00323da4a0.png)

Regards, 
Félix.

**Comment by FelixdelasPozas** [comment]
Hi @iHastr .

The version 1.20 [has been released](https://github.com/FelixdelasPozas/TrayWeather/releases/tag/1.20.0). In the **misc options** tab in the configuration dialog is the option to swap tray icons. I've tested it in Windows 7 without any problem but I'll leave the issue open until I have confirmation that your problem has been solved. 

Regards,
Félix.
